/*
 * Robust age data for Brain Maturation Simulator.
 * Each age entry includes Tanner stage, cognition and behavior HTML with formatting,
 * a maturation notes HTML, optional image filename, and list of sources
 * as objects with text and URL. You can extend entries as needed.
 */

const AGE_DATA = {
  6: {
    introductionHtml: `
        <p>Welcome to the Brain Maturation Simulator! This tool helps you explore how the brain develops from ages 6 to 20. It shows changes in different brain areas over time, using colors: red means immature (not fully developed), and blue means mature (fully developed). You can drag the slider to see what happens at each age.</p>
        <p>This simulation is based on the scientific paper "Dynamic mapping of human cortical development during childhood through early adulthood" by Nitin Gogtay, Jay N. Giedd, and colleagues, published in PNAS in 2004. The study used MRI scans of 13 healthy children over time (from ages 4 to 21) to track how gray matter in the brain thins as it matures. Key findings: Brain development happens in a back-to-front pattern. Basic areas like the occipital lobe (for vision) mature first (around ages 7-9), followed by the parietal lobe (for body awareness and senses, ages 8-12), then the temporal lobe (for emotions and memory, ages 13-17), and finally the frontal lobe (for decision-making and planning, ages 17-20). This matches how kids' thinking and behavior improve as they grow up.</p>
        <p><strong>How to Use the Simulator:</strong></p>
        <ul>
            <li><strong>Age Slider:</strong> Move this to pick an age between 6 and 20. The brain picture will change colors to show which parts are developing. Below, you'll see info about thinking skills, behaviors, and body changes at that age.</li>
            <li><strong>Disorder (Freeze All) Checkbox:</strong> Check this to stop all brain growth, milestones, and body changes at the current age. It shows what might happen with some developmental disorders that slow or stop normal brain maturation.</li>
            <li><strong>Freeze Milestones Checkbox:</strong> This pauses the growth of thinking, social, and behavior skills at the chosen age. It helps see how stopping learning affects overall development.</li>
            <li><strong>Freeze Tanner Checkbox:</strong> Tanner stages track body changes during puberty (like growing taller, developing breasts or muscles). Checking this freezes those changes, like what puberty blockers do. Puberty blockers are medicines that pause puberty temporarily, stopping hormone surges that affect body and brain growth. This can give time for decisions but may impact how the brain develops since hormones help shape it.</li>
            <li><strong>Gender Affirming Hormones Checkbox:</strong> This simulates starting gender-affirming hormone therapy after puberty blockers. It uses hormones from the opposite sex (like estrogen for someone assigned male at birth). It keeps puberty stages frozen, but the effects on brain and behavior growth are not fully known yet—research is still ongoing. In the simulator, it shows question marks for brain milestones to highlight the uncertainty.</li>
        </ul>
        <p>Start by moving the slider to age 7 or higher to see the brain in action!</p>
    `,
    image: 'introduction.jpg', // Optional: Replace with your image if available
    sources: [
        { text: 'Dynamic mapping of human cortical development during childhood through early adulthood (Gogtay et al., PNAS, 2004)', url: 'https://www.pnas.org/doi/10.1073/pnas.0402680101' }
    ]
    },
    // ... other age entries (7–20) ...
  7: {
    tannerStage: 'Stage 1',
    // Cognitive development description with citations and HTML formatting
    cognitionHtml: `<p>At seven, children enter <strong>Piaget’s concrete operational stage</strong>. They develop a solid grasp of time — days of the week, months and seasons — and can solve simple problems like basic addition or subtraction using objects. Their reasoning still focuses on one variable at a time, so multi‑factor or abstract problems remain difficult. Children begin sorting objects by size, shape or colour and understand cause‑and‑effect in everyday situations. Memory and classification skills improve, laying the groundwork for more complex thought.</p>`,
    // Social and emotional milestones
    socialEmotionalHtml: `<p>Empathy emerges: seven‑year‑olds become aware of others’ feelings and may mirror the moods of people around them. They start overcoming early childhood fears, yet new anxieties arise—fear of new social situations or of being judged by adults. They care deeply about doing things the “right” way and can feel embarrassed by mistakes. Same‑gender friendships form, and trust grows; group play alternates with solitary or parallel play. Conflict resolution is rudimentary, with adults still needed to mediate when disagreements feel black‑and‑white.</p>`,
    // Play and behaviour description
    playBehaviorHtml: `<p>Play becomes more sophisticated and rule‑based. Many seven‑year‑olds can follow rules and appreciate fairness in turn‑taking. They role‑play characters from school or media, and start enjoying board games or sports with clear rules. Better control of behaviour and emotion allows them to cope with winning and losing, though coaching in sportsmanship helps. Sharing and negotiating improve, and children take pride in helping adults. Self‑care skills advance: most can dress themselves and handle simple chores independently.</p>`,
    // Gender differences description
    genderDifferencesHtml: `<p>Boys and girls share more similarities than differences, but some patterns appear. Girls may have a slight edge in language and fine motor skills, leading to larger vocabularies and more complex speech. Boys often engage in more physical, rough‑and‑tumble play and may be impulsive. Conflicts among boys tend to centre on competition or dominance, while girls’ disputes may revolve around relationships or feeling left out. Physically, all seven‑year‑olds grow steadily (around 6 cm and 3 kg per year) and improve coordination — swimming, climbing and biking with greater skill.</p>`,
    // Neurodiversity description (ADHD/Autism)
    neurodiversityHtml: `<p>Seven‑year‑olds with ADHD may appear immature compared to peers. Because ADHD brains develop on a delayed timetable — frontal regions may mature up to three years later than typical — they struggle with sitting still, following instructions and inhibiting impulses. This becomes noticeable in structured settings like school, where they need frequent redirection or support for turn‑taking. Autistic children may prefer solitary or parallel play and find unwritten rules of sharing or adapting to others’ ideas challenging. They need support to imagine others’ thoughts and to take turns, and often connect through shared routines or interests rather than long emotional exchanges. Patience and structured guidance from adults help them build social connections.</p>`,
    // Maturation notes for the brain
    maturationNotesHtml: `<p>Primary sensorimotor cortices (occipital and parietal regions) begin pruning; early cerebellar maturation supports basic coordination. Lower‑order cortical regions mature before higher‑order association areas.</p>`,
    // Optional image illustrating development
    image: 'assets/age7.png',
    // List of sources with citations and links
    sources: [
      { text: 'Kaiser Permanente – Milestones for 7‑year‑olds', url: 'https://healthy.kaiserpermanente.org/health-wellness/health-encyclopedia/he.milestones-for-7-year-olds.ue5719' },
      { text: 'Dynamic mapping of human cortical development (PNAS, 2004)', url: 'https://www.pnas.org/doi/10.1073/pnas.0402680101' }
    ]
  },
  8: {
    tannerStage: 'Stage 1–2',
    cognitionHtml: `<p>Eight‑year‑olds follow more complex instructions and start solving problems mentally without always relying on objects. They organise information into categories and often run simple “experiments” to see how things work. Many can read and write independently and learn around twenty new words a day. They begin to appreciate that situations have more than one viewpoint, even if they still struggle to fully accept differing perspectives. Attention spans lengthen, but distractions remain abundant.</p>`,
    socialEmotionalHtml: `<p>Eight‑year‑olds invest heavily in friendships. Peer acceptance becomes important, and relationships deepen around shared interests and trust. They develop a playful sense of humour and may compare themselves with peers, which can affect self‑esteem. Emotion regulation improves — tantrums are rare and they use words to express anger or sadness. They can negotiate in conflicts and show genuine concern when a friend or sibling is upset. Yet boundary‑testing (sneaky behaviour when they think they won’t get caught) persists as moral reasoning develops.</p>`,
    playBehaviorHtml: `<p>Play at eight is imaginative and social. Children love group games, sports, board games and forming clubs or secret societies. They cooperate toward common goals, building forts or staging performances, and expect fair play from peers. Losing still stings, though many cope better than at younger ages. Independence rises — they manage morning routines with minimal help and take pride in small responsibilities like feeding pets or setting the table. Collections and hobbies emerge, and behaviour becomes more self‑regulated, though impulse control is still developing.</p>`,
    genderDifferencesHtml: `<p>Gender differences become noticeable. Girls often retain an advantage in verbal skills and may write longer stories, while boys lean toward physical or competitive play. Girls tend to play in smaller groups and value inclusive relationships, whereas boys gravitate to larger, more competitive games. Around eight, some girls enter mild pre‑pubertal growth (breast buds and height spurts), while most boys remain in a child‑like phase. Both genders benefit from learning empathy and fair play.</p>`,
    neurodiversityHtml: `<p>An eight‑year‑old with ADHD continues to struggle with attention and self‑control amid increasing academic demands. Tasks like multi‑step math or reading long passages can be challenging; they may rush through work or interrupt others. Yet their creativity and energy thrive in interactive, movement‑based learning. Autistic eight‑year‑olds may progress to parallel or associative play but still find cooperative play challenging. Structured games and clear rules provide comfort, and they may have fewer friendships — not from lack of interest but due to lagging social skills. Structured playdates and interest‑based clubs can help them interact with peers.</p>`,
    maturationNotesHtml: `<p>Dorsal parietal cortex begins grey‑matter reduction; occipital lobe continues maturing; cerebellar development advances fine motor skills. Higher‑order temporal and frontal circuits remain comparatively immature.</p>`,
    image: 'assets/age8.png',
    sources: [
      { text: 'Raising Children Network – Eight‑year‑old development', url: 'https://raisingchildren.net.au' },
      { text: 'Dynamic mapping of human cortical development (PNAS, 2004)', url: 'https://www.pnas.org/doi/10.1073/pnas.0402680101' }
    ]
  },
  9: {
    tannerStage: 'Stage 1–2',
    cognitionHtml: `<p>Nine-year-olds are firmly in <strong>Piaget’s concrete operational stage</strong>, displaying logical thinking in everyday contexts. They grasp conservation (e.g., understanding that a tall, narrow glass holds the same volume as a short, wide one) and can consider multiple aspects of a situation simultaneously. Problem-solving improves; they tackle multi-step school problems, like math word problems involving addition and subtraction, without losing track. Many develop interests in collections or classifications, organizing items like trading cards or becoming experts on topics like insects or sports stats. Reading shifts to learning from text, with many reading chapter books independently and summarizing main points. Vocabulary grows, and they enjoy puns and wordplay, often writing stories or reports. Abstract reasoning is emerging but limited; they handle concrete “what if” scenarios but struggle with purely hypothetical questions. Attention spans lengthen, though breaks are needed for long tasks. They show early metacognition, recognizing when they don’t understand something and developing study strategies, like planning ahead in games or schoolwork.</p>`,
    socialEmotionalHtml: `<p>Nine-year-olds grow more self-aware and may become self-critical, comparing themselves to peers and worrying about being “normal.” Confidence fluctuates; they might brag about strengths one day and feel inadequate the next. Empathy and perspective-taking improve, allowing them to infer others’ feelings and offer comfort. Friendships deepen, based on trust and shared values, but conflicts can be emotionally intense. They resolve minor disputes independently through compromise or humor but need adult guidance for bigger issues. Peer groups and belonging are significant, with peer pressure emerging subtly, influencing clothing or activities. Morality becomes internalized; they value fairness and may call out injustices. Emotional regulation improves, with fewer meltdowns, and they use coping strategies like retreating to cool off. Some experience early pre-adolescent mood swings, especially girls, due to hormonal changes. They admire role models (teachers, sports stars), aligning with <strong>Erikson’s industry vs. inferiority stage</strong>, seeking competence.</p>`,
    playBehaviorHtml: `<p>Nine-year-olds engage in structured, active play, joining organized sports, music lessons, or clubs like science or scouting. They enjoy strategic group games (e.g., capture the flag, complex board games) and elaborate imaginative play, creating ongoing sagas or imaginary worlds. Collections and hobbies (stickers, model kits) reflect persistence and organization. They value teamwork in sports or school projects, showing pride in group contributions. Behaviorally, they are more independent, handling routines like morning prep or simple snacks and seeking grown-up privileges like walking to a friend’s house. They test limits, sneaking extra screen time or bending rules, but feel guilty if caught, especially if someone is hurt. In school, they manage complex projects and routines, needing physical activity to avoid restlessness. Motor skills advance, with accurate throwing, confident biking, and neat handwriting, balancing maturity with childhood enthusiasm.</p>`,
    genderDifferencesHtml: `<p>Gender differences become more pronounced as some girls show early pubertal signs (breast buds, growth spurts), while most boys remain pre-pubertal, affecting social dynamics and self-consciousness. Girls often excel in verbal and social skills, engaging in collaborative play, while boys prefer competitive or physical activities like sports or video games. Boys’ conflicts focus on competition or dominance, often resolved directly, while girls’ disputes center on relationships and inclusion, sometimes using subtle social strategies. Both genders prefer same-gender friend groups, with mild “cooties” sentiments emerging. Academically, girls may have an edge in writing, boys in spatial tasks, though encouragement breaks stereotypes. Nonconforming interests (e.g., a boy in theater, a girl in gaming) may face peer challenges, needing adult support. Physically, growth continues steadily, with improved coordination for both.</p>`,
    neurodiversityHtml: `<p>Nine-year-olds with ADHD face increasing school demands, struggling with organization (messy desks, forgotten homework) and impulsivity, like blurting answers or interrupting. Their creativity shines in hands-on or active learning, but they may need visual organizers or movement breaks. The ADHD brain’s frontal lobe delay makes them seem less mature, behaving like younger peers in self-regulation. Autistic children may prefer solitary or parallel play, finding cooperative play and unwritten social rules challenging. They connect through shared interests or routines but may struggle with perspective-taking or turn-taking. Fewer friendships result from social skill gaps, not lack of interest; structured playdates or clubs help. Both need targeted support (e.g., therapy, accommodations) to bridge academic and social gaps, leveraging strengths like ADHD creativity or autistic focus on interests.</p>`,
    maturationNotesHtml: `<p>Frontal and temporal cortices continue developing, supporting improved logic and memory. Synaptic pruning in parietal regions enhances processing efficiency. Prefrontal areas remain immature, limiting impulse control and complex planning.</p>`,
    image: 'assets/age9.png',
    sources: [
      { text: 'Kaiser Permanente – Milestones for 9–11-year-olds', url: 'https://healthy.kaiserpermanente.org/health-wellness/health-encyclopedia/he.milestones-for-9-to-11-year-olds.te7266' },
      { text: 'Raising Mediators – Conflict Resolution in Children', url: 'https://raisingmediators.com' },
      { text: 'NIMH – ADHD Brain Development', url: 'https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd' },
      { text: 'Dynamic mapping of human cortical development (PNAS, 2004)', url: 'https://www.pnas.org/doi/10.1073/pnas.0402680101' }
    ]
  },
  10: {
    tannerStage: 'Stage 2',
    cognitionHtml: `<p>Ten-year-olds show systematic thinking, planning school projects by breaking tasks into steps with guidance. They approach <strong>Piaget’s formal operational stage</strong>, handling simple abstract ideas like proverbs (“don’t cry over spilled milk” means not worrying over small mistakes). They manage fractions and decimals in math, requiring abstract thought, and switch between tasks with improved cognitive flexibility. Attention spans extend to 20–30 minutes on engaging tasks, and they develop study strategies through metacognition (e.g., “I remember better with rhymes”). Problem-solving is creative, applying learned principles to new contexts, like using multiplication for planning. They categorize knowledge (e.g., animals by class) and enjoy collections, tracking details systematically. Memory strengthens, enabling memorization of complex game rules or play lines. Early moral reasoning emerges, questioning rules’ fairness, marking the start of abstract ethical thinking, though nuanced reasoning is still developing.</p>`,
    socialEmotionalHtml: `<p>Ten-year-olds stand at adolescence’s threshold, blending childlike and pre-teen behaviors. They prioritize best friends or tight groups, with same-gender friendships dominant, though some develop innocent crushes. Peer approval influences clothing or hobbies, yet they seek family support when stressed. Self-esteem fluctuates; they recognize strengths and weaknesses but may judge themselves harshly. Mood swings emerge from hormonal changes and social pressures, with complex emotions like excitement and nervousness coexisting. Empathy grows; they organize acts of kindness, like get-well cards for classmates. <strong>Erikson’s industry vs. inferiority stage</strong> drives their need for competence, but social rejection or bullying can foster inferiority. They desire autonomy, asserting opinions and negotiating privileges, yet admire adults like teachers. Emotional regulation improves, using coping strategies, though occasional outbursts occur under stress.</p>`,
    playBehaviorHtml: `<p>Ten-year-olds engage in organized activities like team sports, music, or clubs, mastering complex rules and valuing camaraderie. Play shifts to strategic games (board games, video games) or elaborate make-believe with ongoing storylines. Creative hobbies like drawing or writing flourish, often tech-driven (e.g., animations). They show responsibility, managing routines like packing backpacks and doing chores like vacuuming. Screen time increases, adopting peer trends like viral dances, requiring guidance on limits. They handle competition better, though peer-driven “cool” behaviors influence actions. Physical energy demands outlets to prevent restlessness; motor skills allow precise tasks like neat handwriting. They take pride in ownership (e.g., collections, room decor) and fairness, calling out rule-breaking, though some test limits like sneaking screen time, seeking independence.</p>`,
    genderDifferencesHtml: `<p>Puberty begins for many girls (breast development, growth spurts), while boys often remain pre-pubertal, creating physical and social gaps. Girls may feel self-conscious about body changes, while boys feel “behind.” Girls excel in verbal skills, engaging in emotional sharing and collaborative play, while boys favor competitive activities like sports or gaming. Girls’ conflicts involve relationships, resolved subtly, while boys’ focus on competition, often direct. Academically, girls may lead in language arts, boys in spatial tasks, though encouragement equalizes performance. Same-gender groups dominate, but some curiosity about the opposite gender emerges. Nonconforming interests face peer pressure, needing support. Girls face more mature expectations, boys feel tolerance for rowdiness, reflecting societal biases.</p>`,
    neurodiversityHtml: `<p>Ten-year-olds with ADHD struggle with middle school’s demands, like multi-teacher schedules, leading to disorganization or forgotten assignments. Impulsivity causes social missteps (e.g., interrupting), but their creativity shines in engaging tasks. Movement breaks and planners aid focus. Autistic children face widening social gaps as peers’ interactions grow complex. They prefer structured or interest-based play, struggling with reciprocal friendships, which may lead to loneliness. Clubs or shared interests foster connections. Anxiety rises from social differences or routine changes; sensory issues (e.g., loud cafeterias) cause distress. Both benefit from accommodations like IEPs, social skills training, or therapy. ADHD creativity and autistic focus are strengths, needing encouragement to build confidence and peer acceptance.</p>`,
    maturationNotesHtml: `<p>Prefrontal cortex development supports planning and self-regulation, though still immature. Temporal lobe maturation enhances language and memory. Synaptic pruning continues in parietal and occipital regions, refining sensory processing.</p>`,
    image: 'assets/age10.png',
    sources: [
      { text: 'Kaiser Permanente – Milestones for 9–11-year-olds', url: 'https://healthy.kaiserpermanente.org/health-wellness/health-encyclopedia/he.milestones-for-9-to-11-year-olds.te7266' },
      { text: 'Child Mind Institute – ADHD in Children', url: 'https://childmind.org/topics/adhd' },
      { text: 'Dynamic mapping of human cortical development (PNAS, 2004)', url: 'https://www.pnas.org/doi/10.1073/pnas.0402680101' }
    ]
  },
  11: {
    tannerStage: 'Stage 2–3',
    cognitionHtml: `<p>Eleven-year-olds bridge concrete and abstract thought, entering <strong>Piaget’s formal operational stage</strong>. They handle simple hypotheticals (e.g., “What if Earth had no moon?”) and consider multiple perspectives, recognizing issues aren’t black-and-white. Future-oriented thinking emerges, linking actions like homework to outcomes like test performance. Adolescent egocentrism appears, with an “imaginary audience” making them self-conscious (e.g., “Everyone notices my pimple”). They employ memory aids like note-taking and question information sources, showing early critical thinking. Math and science involve variables, algebra, and ratios, requiring abstract logic. Language skills include sarcasm and figurative speech, with a knack for witty quips. Moral reasoning considers intent, distinguishing accidental from intentional rule-breaking. They debate family traditions, practicing logic, though abstract ethical reasoning is still developing.</p>`,
    socialEmotionalHtml: `<p>Eleven-year-olds explore identity, trying different styles or personas, per <strong>Erikson’s identity vs. role confusion stage</strong>. They pull away from family, prioritizing friends, with peer approval shaping choices. Moodiness increases from puberty and social pressures, with emotional swings between childlike and teen behaviors. Friendships grow intimate, forming cliques, but exclusion or bullying peaks, impacting self-esteem. Romantic crushes emerge, with shy “relationships” or teasing, causing intense emotions. They desire privacy and autonomy, arguing for privileges, but still seek parental support in crises. Empathy allows altruistic acts, like supporting bullied peers, and some develop idealistic views on social issues. Self-consciousness and complex emotions like loneliness surface, requiring non-judgmental adult support to navigate early adolescence.</p>`,
    playBehaviorHtml: `<p>Play shifts to recreation and socializing. Eleven-year-olds engage in extracurriculars like sports, music, or clubs, tying identity to roles like “athlete” or “artist.” They enjoy competitive games, video games, or creative pursuits like drawing or tech-based projects (e.g., animations). Socializing involves “hanging out,” talking, or browsing online, needing supervision for safe media use. They handle competition well but test limits, like sneaking forbidden media, driven by curiosity. In school, they manage group projects and leadership roles, craving responsibility. Risk-taking emerges (e.g., bike stunts), reflecting an active reward system. Sleep shifts later due to puberty, causing morning grogginess. They focus intensely on passions but struggle with unengaging tasks, balancing maturity with impulsivity.</p>`,
    genderDifferencesHtml: `<p>Puberty widens gender gaps: most girls have breast development and growth spurts, some menstruating, while boys begin early changes, creating physical disparities. Girls appear more mature, excelling in organization and verbal tasks, while boys may act out impulsively. Girls’ friendships are emotionally intense, with relational conflicts; boys’ are activity-based, with direct resolutions. Girls show earlier romantic interest, while boys catch up. Academic confidence may dip for girls in STEM, boys in language arts, due to stereotypes. Girls face body image pressures; boys worry about height or strength. Societal expectations pressure girls to be mature, boys to be tough. Nonconforming youth may explore gender identity, needing support to navigate peer reactions.</p>`,
    neurodiversityHtml: `<p>ADHD eleven-year-olds struggle with middle school’s organizational demands, risking academic gaps without supports like planners or IEPs. Impulsivity leads to riskier social behaviors (e.g., interrupting, peer pressure susceptibility), but creativity aids leadership. Autistic children face heightened social challenges as peer interactions grow subtle, risking isolation or bullying. Structured clubs help, leveraging interests like gaming for connections. Anxiety spikes from social differences or sensory overload (e.g., crowded halls). Masking exhausts them, potentially causing home meltdowns. Both benefit from accommodations, social skills training, and strengths-based encouragement (e.g., ADHD spontaneity, autistic expertise). Mental health monitoring is key, as anxiety or depression may emerge from social pressures.</p>`,
    maturationNotesHtml: `<p>Prefrontal cortex maturation supports abstract thinking, though impulse control lags. Limbic system development heightens emotional reactivity. Synaptic pruning in frontal and temporal regions enhances cognitive efficiency.</p>`,
    image: 'assets/age11.png',
    sources: [
      { text: 'Kaiser Permanente – Milestones for 9–11-year-olds', url: 'https://healthy.kaiserpermanente.org/health-wellness/health-encyclopedia/he.milestones-for-9-to-11-year-olds.te7266' },
      { text: 'BrainFacts – Adolescent Brain Development', url: 'https://www.brainfacts.org/brain-anatomy-and-function/brain-development' },
      { text: 'Child Mind Institute – ADHD in Children', url: 'https://childmind.org/topics/adhd' }
    ]
  },
  12: {
    tannerStage: 'Stage 3–4',
    cognitionHtml: `<p>Twelve-year-olds often enter <strong>Piaget’s formal operational stage</strong>, mastering abstract reasoning and hypotheticals like “What if we lived on Mars?” They debate ethics or justice, seeing multiple perspectives, and challenge norms with logic. Metacognition improves, with teens reflecting on study habits (e.g., “I learn better at night”). Schoolwork involves algebra, literary analysis, and experimental design, requiring multi-variable thinking. The “personal fable” makes them feel unique or invincible, influencing risk-taking. They critically assess sources, distinguishing reliable information, and memorize vast details in areas of interest (e.g., game lore). Executive function varies; some struggle with organization, needing planners. Creativity and empathy grow, enabling complex social analysis, though adolescent egocentrism causes self-focused biases like the “imaginary audience.”</p>`,
    socialEmotionalHtml: `<p>At 12, teens fully enter adolescence, per <strong>Erikson’s identity vs. role confusion stage</strong>, experimenting with personas to define themselves. Peer influence peaks, driving conformity in style or behavior; family ties weaken as friends dominate. Mood swings intensify from hormones and social pressures, with heightened self-consciousness. Cliques and popularity hierarchies form, with bullying risks like cyberbullying affecting self-esteem. Romantic relationships start, with intense emotions from crushes or breakups. They seek autonomy, arguing over rules, but need parental support in crises. Complex emotions like ambivalence or existential wondering emerge, often expressed through journaling or music. Many embrace social causes, showing empathy and idealism, though family conflicts rise as they assert independence.</p>`,
    playBehaviorHtml: `<p>Play becomes socializing and hobbies. Twelve-year-olds immerse in extracurriculars (sports, theater) or creative pursuits (fanfiction, video content), tying identity to activities. Socializing involves unstructured “hanging out,” gaming, or group outings, with heavy digital engagement needing oversight. Risk-taking increases (e.g., sneaking out, minor dares), driven by reward-seeking and peer pressure. They manage schoolwork and chores (e.g., cooking, laundry) but question rules, negotiating curfews. Procrastination rises with social distractions. Sleep shifts later, causing fatigue; healthy habits need reinforcement. They excel in passions but slack in unengaging tasks, showing leadership in trusted roles while testing boundaries to feel adult-like.</p>`,
    genderDifferencesHtml: `<p>Most girls near puberty’s end, appearing mature, while boys enter it, creating physical gaps. Girls excel in verbal tasks and organization, while boys may lag in self-regulation, facing more disciplinary issues. Girls’ friendships are emotionally intense, prone to relational aggression; boys’ are activity-based, with direct conflicts. Girls show stronger romantic interest; boys catch up. Girls face body image pressures, risking low self-esteem; boys worry about physical development. Gender norms solidify, with nonconforming teens facing teasing. Girls may internalize issues (anxiety), boys externalize (acting out). Encouraging cross-gender interests and addressing stereotypes supports balanced development.</p>`,
    neurodiversityHtml: `<p>ADHD twelve-year-olds struggle with high school’s demands, risking academic gaps from disorganization. Impulsivity fuels riskier behaviors (e.g., skipping class), needing strategies like planners. Their spontaneity aids social charm but can annoy peers. Autistic teens face social isolation as peer dynamics grow complex, risking bullying or anxiety. Interest-based clubs bridge connections, but sensory overload (e.g., noisy cafeterias) and routine changes challenge them. Masking causes exhaustion; home meltdowns are common. Both need accommodations (IEPs, sensory breaks) and strengths-based support (ADHD creativity, autistic expertise). Mental health risks (depression, anxiety) rise, needing monitoring to foster self-esteem and inclusion.</p>`,
    maturationNotesHtml: `<p>Limbic system hyperactivity drives emotional intensity and reward-seeking. Prefrontal cortex continues maturing, improving reasoning but not yet impulse control. Cortical thinning in frontal areas enhances abstract thinking efficiency.</p>`,
    image: 'assets/age12.png',
    sources: [
      { text: 'Kaiser Permanente – Milestones for 12–14-year-olds', url: 'https://healthy.kaiserpermanente.org/health-wellness/health-encyclopedia/he.milestones-for-12-to-14-year-olds.te7267' },
      { text: 'BrainFacts – Adolescent Brain Development', url: 'https://www.brainfacts.org/brain-anatomy-and-function/brain-development' },
      { text: 'ResearchGate – Autism and Social Challenges', url: 'https://www.researchgate.net/publication/319401374_Social_challenges_and_supports_from_the_perspective_of_individuals_with_autism_spectrum_disorder' }
    ]
  },
  13: {
    tannerStage: 'Stage 3–5',
    cognitionHtml: `<p>Thirteen-year-olds solidify <strong>Piaget’s formal operational stage</strong>, excelling in abstract reasoning and hypotheticals (e.g., debating Mars colonization). They challenge norms, adopting ideological stances, often extreme, as they test ideas. Schoolwork includes algebra, geometry, and critical literary analysis, handling multi-variable problems. They assess information reliability, vital in the digital age. The “personal fable” fosters perceived invincibility, driving risk-taking. Memory excels in interests (e.g., game details), and metacognition aids study strategies, though some struggle with organization, needing tools like calendars. Creativity and advanced empathy enable social analysis, but egocentrism (e.g., “imaginary audience”) causes self-consciousness. Critical thinking makes them argumentative, practicing logic on their environment.</p>`,
    socialEmotionalHtml: `<p>Thirteen-year-olds prioritize peers over family, seeking independence in <strong>Erikson’s identity vs. role confusion stage</strong>. They experiment with identities (e.g., goth, skater) and conform to peer norms for approval, amplifying self-consciousness. Mood swings peak from hormones, with emotional volatility (e.g., euphoria to despair). Cliques solidify, with bullying risks like cyberbullying impacting self-esteem. Romantic relationships intensify, with first kisses and heartbreak feeling monumental. They desire autonomy, clashing with parents over rules, but need support in crises. Complex emotions (ambivalence, loneliness) emerge, expressed through creative outlets. Idealism drives passion for causes (e.g., activism), though self-focus can seem inconsiderate. Mental health risks like anxiety require vigilance.</p>`,
    playBehaviorHtml: `<p>Play is socializing and hobbies like sports, music, or gaming, central to identity (e.g., “soccer player”). Teens create online content (e.g., TikTok, fanfiction) or engage in group outings, craving independence. Risk-taking rises (e.g., sneaking out, dares), driven by reward-seeking brains. Schoolwork and chores (e.g., babysitting, cooking) are managed, but procrastination and rule-testing (e.g., late curfews) are common. Sleep shifts later, causing fatigue; healthy habits need enforcement. They excel in passions, showing leadership, but slack in unengaging tasks. Digital engagement (social media, gaming) requires monitoring for cyberbullying. Privacy increases, with teens guarding phones or diaries, balancing autonomy with adult oversight.</p>`,
    genderDifferencesHtml: `<p>Girls often complete puberty, appearing mature, while boys are mid-puberty, creating physical and social gaps. Girls excel in verbal tasks and organization, boys face more disciplinary issues from impulsivity. Girls’ friendships are emotionally intense, with relational aggression; boys’ are activity-based, with direct conflicts. Girls show earlier romantic interest; boys catch up. Body image hits girls harder, risking low self-esteem; boys worry about physical development. Gender norms peak, with nonconforming teens facing pressure. Girls may internalize issues (depression), boys externalize (aggression). Sexual behavior faces double standards (boys praised, girls shamed). Encouraging cross-gender interests and supporting identity exploration fosters healthy development.</p>`,
    neurodiversityHtml: `<p>ADHD thirteen-year-olds struggle with high school’s demands, risking academic gaps from disorganization. Impulsivity fuels risky behaviors (e.g., substance experimentation), needing coping strategies. Their charisma aids social bonds but can annoy peers. Autistic teens face social isolation in complex high school dynamics, risking bullying or anxiety. Interest-based clubs help, but sensory issues (e.g., noisy halls) and routine changes challenge them. Masking exhausts, causing meltdowns. Both need accommodations (e.g., IEPs, sensory breaks) and strengths-based support (ADHD creativity, autistic expertise). Mental health risks (depression, anxiety) rise, needing monitoring. Self-advocacy grows, empowering teens to navigate challenges with supportive environments.</p>`,
    maturationNotesHtml: `<p>Prefrontal cortex maturation enhances abstract reasoning, though impulse control remains underdeveloped. Limbic system drives reward-seeking and emotional intensity. Cortical connectivity strengthens, supporting complex cognition but not yet full self-regulation.</p>`,
    image: 'assets/age13.png',
    sources: [
      { text: 'Kaiser Permanente – Milestones for 12–14-year-olds', url: 'https://healthy.kaiserpermanente.org/health-wellness/health-encyclopedia/he.milestones-for-12-to-14-year-olds.te7267' },
      { text: 'NIMH – ADHD and Brain Development', url: 'https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd' },
      { text: 'ResearchGate – Autism and Social Challenges', url: 'https://www.researchgate.net/publication/319401374_Social_challenges_and_supports_from_the_perspective_of_individuals_with_autism_spectrum_disorder' },
      { text: 'Springer – Gender and Self-Esteem in Adolescence', url: 'https://link.springer.com/article/10.1007/s10964-018-0847-1' }
    ]
  },
  14: {
    tannerStage: 'Stage 4–5',
    cognitionHtml: `<p>Fourteen-year-olds exhibit advanced formal operational thinking, engaging in sophisticated debates on ethics, politics, or societal issues. They plan long-term goals, like career paths, and critically evaluate arguments, detecting biases in media or discussions. Schoolwork involves advanced math (e.g., geometry proofs) and analytical essays, requiring evidence-based reasoning. Metacognition matures, allowing self-directed learning strategies, such as prioritizing tasks or seeking resources. The personal fable persists, contributing to idealistic views or underestimating risks. Memory and focus improve for interests, enabling deep dives into topics like coding or history. However, executive function may lag in unmotivating areas, leading to procrastination. Creativity peaks, often channeled into projects or activism, reflecting growing intellectual independence.</p>`,
    socialEmotionalHtml: `<p>At 14, teens deepen identity exploration in <strong>Erikson’s identity vs. role confusion stage</strong>, questioning values and experimenting with subcultures. Peer groups intensify, with strong loyalty but risks of exclusion or cyberbullying eroding self-esteem. Romantic relationships become more serious, involving emotional intimacy and potential heartbreak, heightening vulnerability. Independence surges; they challenge parental authority, seeking privacy and decision-making power, yet rely on family for stability. Mood volatility from hormones and stress can manifest as irritability or withdrawal. Empathy expands, fostering social justice interests. Parenting tips: Maintain open communication, set consistent boundaries, and monitor for mental health signs like persistent sadness (depression), excessive worry (anxiety), or isolation. Early schizophrenia indicators include subtle hallucinations or paranoia—seek professional help if noticed. Encourage healthy outlets like sports to build resilience.</p>`,
    playBehaviorHtml: `<p>Behavior at 14 focuses on structured activities and social experiences, like team sports, clubs, or part-time jobs, building skills and resumes. Hobbies evolve into passions, such as music production or online content creation, often collaborative via apps. Risk-taking may include experimentation (e.g., vaping, skipping school), driven by peer influence—parents should discuss consequences calmly. Independence shows in managing schedules, but procrastination on chores or homework is common. Digital life dominates, with gaming or social media; set screen limits to prevent addiction. Sleep patterns disrupt due to late melatonin release, affecting mood—enforce routines. Leadership emerges in groups, but watch for defiant behaviors signaling stress. Tips: Praise responsibility, involve them in family decisions to foster maturity.</p>`,
    genderDifferencesHtml: `<p>By 14, physical gaps narrow as boys catch up in puberty, but girls often remain ahead in emotional maturity, leading to earlier romantic involvement. Girls may internalize stress, showing higher anxiety or depression rates, while boys externalize through aggression or risk-taking. Girls’ friendships emphasize emotional support, prone to relational conflicts; boys’ focus on shared activities, with competitive dynamics. Academically, girls may outperform in verbal subjects, boys in spatial ones, influenced by stereotypes—encourage balanced pursuits. Body image pressures intensify for girls (e.g., eating disorders), boys (muscle building). Nonconforming teens may face identity challenges; support exploration. Societal expectations persist: girls pressured for likability, boys for toughness.</p>`,
    neurodiversityHtml: `<p>ADHD teens at 14 navigate high school’s demands, often struggling with organization and focus, risking academic slips or frustration. Impulsivity heightens substance risks; medication or therapy helps, alongside planners. Their energy suits creative roles, but social misreads can isolate. Autistic 14-year-olds face amplified social hurdles, with masking leading to burnout or anxiety. Interest-based clubs aid inclusion, but bullying risks rise—monitor for withdrawal. Co-occurring depression is common; early intervention key. Parenting: Advocate for IEPs, teach self-advocacy, watch for mental health red flags like sudden mood changes or isolation, which could signal emerging issues like schizophrenia in neurodivergent youth.</p>`,
    maturationNotesHtml: `<p>Prefrontal cortex continues refining, supporting better planning and risk assessment, though full maturity lags until mid-20s. Limbic-pruning enhances emotional regulation, but social experiences shape neural pathways. Myelination improves cognitive speed.</p>`,
    image: 'assets/age14.png',
    sources: [
      { text: 'HealthyChildren.org – Stages of Adolescence', url: 'https://www.healthychildren.org/English/ages-stages/teen/Pages/Stages-of-Adolescence.aspx' },
      { text: 'NIMH – The Teen Brain: 7 Things to Know', url: 'https://www.nimh.nih.gov/health/publications/the-teen-brain-7-things-to-know' },
      { text: 'Mayo Clinic – Childhood Schizophrenia', url: 'https://www.mayoclinic.org/diseases-conditions/childhood-schizophrenia/symptoms-causes/syc-20354483' },
      { text: 'Talkspace – 20 Expert Tips for Parenting Teenagers', url: 'https://www.talkspace.com/blog/parenting-a-teenager/' }
    ]
  },
  15: {
    tannerStage: 'Stage 4–5',
    cognitionHtml: `<p>Fifteen-year-olds demonstrate robust abstract thinking, debating complex topics like climate change or inequality with evidence. They set personal goals, like college prep, and use critical analysis in essays or science labs. Metacognition advances, enabling independent study habits and time management. The imaginary audience fades slightly, but personal fable persists, influencing optimistic risk views. Focus deepens for passions, supporting advanced projects like research papers. However, distractions from social life can cause inconsistent performance. Creativity integrates with logic, fostering innovation in arts or tech. Overall, cognition approaches adult levels, with experience gaps.</p>`,
    socialEmotionalHtml: `<p>Fifteen-year-olds solidify identity, often through activism or hobbies, in <strong>Erikson’s stage</strong>. Peer validation drives behaviors, with intense friendships but vulnerability to drama or rejection. Romantic ties deepen, exploring intimacy, potentially leading to emotional ups/downs. Autonomy battles intensify; they demand freedom but need guidance on decisions. Emotional regulation improves, but stress from school/relationships can trigger anxiety. Parenting: Listen actively, respect privacy, but discuss risks like substance use. Watch for depression (hopelessness, appetite changes), anxiety (avoidance), or schizophrenia signs (delusions, disorganized speech)—early intervention crucial. Foster resilience via open talks and professional support if needed.</p>`,
    playBehaviorHtml: `<p>At 15, activities include jobs, volunteering, or advanced hobbies like coding clubs, building resumes. Socializing via parties or online, with increased independence (e.g., driving learner’s permit). Risk behaviors peak (e.g., alcohol trials)—enforce curfews, know friends. Digital habits intensify; monitor for addiction. Sleep deficits from late nights affect focus—promote routines. Leadership in school groups emerges, but defiance may signal stress. Tips: Encourage balanced schedules, praise efforts, involve in household rules to teach responsibility, and discuss consequences without lectures.</p>`,
    genderDifferencesHtml: `<p>Physical maturity evens out, but girls often show higher verbal/emotional skills, boys physical strength. Girls face greater body scrutiny, risking eating disorders; boys pressure for masculinity, leading to aggression. Girls internalize emotions (higher depression), boys externalize (risk-taking). Romantic dynamics: girls seek emotional bonds, boys physical. Stereotypes persist in interests; challenge them. Nonconformity may increase self-exploration.</p>`,
    neurodiversityHtml: `<p>ADHD 15-year-olds battle distractions in demanding classes, benefiting from apps or coaching for organization. Impulsivity risks unsafe choices; therapy aids. Autistic teens may mask heavily, risking burnout/anxiety; clubs provide safe spaces. Co-morbidities like depression rise—watch for withdrawal. Parenting: Support IEPs, teach advocacy, monitor for emerging psychosis (e.g., hallucinations in schizophrenia-prone neurodivergent youth).</p>`,
    maturationNotesHtml: `<p>Frontal lobe myelination boosts decision-making, though reward-seeking dominates. Pruning refines neural efficiency, influenced by experiences. Full prefrontal maturity nears but incomplete until 25.</p>`,
    image: 'assets/age15.png',
    sources: [
      { text: 'NIMH – The Teen Brain: 7 Things to Know', url: 'https://www.nimh.nih.gov/health/publications/the-teen-brain-7-things-to-know' },
      { text: 'PMC – Age of Onset of Mental Disorders', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1925038/' },
      { text: 'Raising Children Network – Pre-teen and Teenage Brain Development', url: 'https://raisingchildren.net.au/pre-teens/behaviour/encouraging-good-behaviour/encouraging-positive-behaviour-teens' },
      { text: 'PMC – Heightened Anxiety and Depression Among Autistic Adolescents', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9630808/' }
    ]
  },
  16: {
    tannerStage: 'Stage 5',
    cognitionHtml: `<p>Sixteen-year-olds master complex reasoning, analyzing global issues or ethical dilemmas with nuance. They plan futures, like job applications, and use advanced critical thinking in debates or research. Metacognition supports self-motivated learning, like online courses. Personal fable diminishes, improving risk assessment. Focus sustains for exams or projects, with strong memory for details. Creativity merges with practicality, aiding entrepreneurship or arts.</p>`,
    socialEmotionalHtml: `<p>Identity consolidates, with teens asserting values through work or causes. Peers remain key, but family bonds may strengthen selectively. Romantic relationships mature, focusing on mutual support. Independence includes driving, heightening responsibility. Emotional stability grows, but academic stress can spark anxiety. Parenting: Encourage goal-setting, discuss mental health openly. Signs of depression (isolation), anxiety (panic), or schizophrenia (hallucinations, paranoia) warrant immediate help—family history increases risk.</p>`,
    playBehaviorHtml: `<p>Activities include work, internships, or serious hobbies like band or sports teams. Social life involves dates or events; monitor for unsafe parties. Risk-taking may involve driving recklessly—teach safety. Digital balance needed; promote offline time. Tips: Trust with earned freedom, guide financial decisions, foster empathy through volunteering.</p>`,
    genderDifferencesHtml: `<p>Maturity levels align, but girls show higher empathy, boys sensation-seeking. Girls higher internalizing disorders, boys externalizing. Interests diversify, but stereotypes linger—promote equity. Romantic expectations differ: girls emotional depth, boys physical.</p>`,
    neurodiversityHtml: `<p>ADHD teens manage better with routines, but transitions (e.g., college) challenge; coaching helps. Autistic 16-year-olds may thrive in niches but struggle socially; support self-advocacy. Watch for co-occurring issues like anxiety or early psychosis signs.</p>`,
    maturationNotesHtml: `<p>Prefrontal integration enhances judgment, reducing impulsivity. Social experiences solidify pathways. Brain nears 95% adult size, with ongoing refinement.</p>`,
    image: 'assets/age16.png',
    sources: [
      { text: 'Cleveland Clinic – Adolescent Development', url: 'https://my.clevelandclinic.org/health/articles/7060-adolescent-development' },
      { text: 'WebMD – Schizophrenia Onset: When It Happens and Early Warning Signs', url: 'https://www.webmd.com/schizophrenia/schizophrenia-onset-symptoms' },
      { text: 'Empowering Parents – Rules and Boundaries for Older Children and Teens', url: 'https://www.empoweringparents.com/article/rules-boundaries-and-older-children-part-i/' },
      { text: 'Frontiers – Adolescent Gender Differences in Cognitive Control', url: 'https://www.frontiersin.org/journals/behavioral-neuroscience/articles/10.3389/fnbeh.2018.00073/full' }
    ]
  },
  17: {
    tannerStage: 'Stage 5',
    cognitionHtml: `<p>Seventeen-year-olds exhibit near-adult cognition, synthesizing information for essays or debates on multifaceted topics. They strategize for college or careers, using foresight and analysis. Critical thinking debunks misinformation effectively. Metacognition optimizes learning, like adaptive studying. Focus endures for high-stakes tasks, with integrated creativity and logic.</p>`,
    socialEmotionalHtml: `<p>Teens at 17 refine identity, balancing independence with relationships. Peers influence less as self-confidence grows. Romantic bonds emphasize compatibility. Emotional maturity allows better conflict resolution. Parenting: Support transitions, discuss life skills. Monitor for mental health: persistent low mood (depression), irrational fears (anxiety), or emerging schizophrenia (disorganized thoughts)—early therapy vital.</p>`,
    playBehaviorHtml: `<p>Focus on pre-adult pursuits: jobs, volunteering, advanced classes. Socializing mature, like group trips. Risks decrease with better judgment, but discuss safe driving/partying. Tips: Encourage financial literacy, mentor decision-making, celebrate achievements to build confidence.</p>`,
    genderDifferencesHtml: `<p>Differences minimize, but girls often report higher anxiety, boys risk behaviors. Empathy gaps narrow. Interests overlap more; support non-traditional paths. Romantic views converge on equality.</p>`,
    neurodiversityHtml: `<p>ADHD 17-year-olds use strategies for independence, but stress amplifies symptoms; ongoing support needed. Autistic teens prepare for adulthood, focusing on strengths; anxiety common. Watch for co-morbid psychosis signs.</p>`,
    maturationNotesHtml: `<p>Full prefrontal maturation approaches, enhancing self-control. Neural plasticity supports learning, shaped by experiences. Brain at ~95% adult function.</p>`,
    image: 'assets/age17.png',
    sources: [
      { text: 'Stanford Children’s Health – Cognitive Development in Adolescence', url: 'https://www.stanfordchildrens.org/en/topic/default?id=cognitive-development-in-adolescence-90-P01594' },
      { text: 'Psychiatry.org – Warning Signs of Mental Illness', url: 'https://www.psychiatry.org/patients-families/warning-signs-of-mental-illness' },
      { text: 'Your Teen Mag – 20 Pieces of Advice Every Teenage Girl Needs to Hear', url: 'https://yourteenmag.com/family-life/communication/for-every-teen-girl' },
      { text: 'PMC – Gender Difference in the Change of Adolescents’ Mental Health', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8896070/' }
    ]
  },
  18: {
    tannerStage: 'Stage 5',
    cognitionHtml: `<p>Eighteen-year-olds achieve adult-like reasoning, evaluating ethics or policies with depth. They plan independently, like budgeting for college. Critical analysis aids decision-making, debunking biases. Metacognition refines lifelong learning habits. Focus and memory support complex tasks, with integrated abstract and practical thinking.</p>`,
    socialEmotionalHtml: `<p>At 18, young adults transition to independence, solidifying identity via work/education. Relationships mature, emphasizing mutual respect. Emotional resilience grows, but life changes can trigger anxiety. Parenting: Offer guidance as equals, respect autonomy. Signs of issues: chronic hopelessness (depression), excessive rumination (anxiety), or schizophrenia onset (delusions)—encourage therapy. Foster open dialogue on mental health.</p>`,
    playBehaviorHtml: `<p>Activities include college, jobs, or travel, with leisure like fitness or events. Risks involve alcohol; discuss moderation. Tips: Teach budgeting, support goals, model healthy habits to ease adulthood transition.</p>`,
    genderDifferencesHtml: `<p>Gaps diminish; both genders show similar maturity. Persistent trends: women higher empathy, men sensation-seeking. Mental health: women more internalizing, men externalizing. Promote equity in opportunities.</p>`,
    neurodiversityHtml: `<p>ADHD adults manage with tools, but transitions challenge; vocational support helps. Autistic 18-year-olds navigate independence, leveraging strengths; anxiety persists. Monitor for emerging severe issues like psychosis.</p>`,
    maturationNotesHtml: `<p>Brain nears full maturity, with prefrontal-limbic balance improving judgment. Ongoing plasticity allows adaptation. Social experiences finalize pathways.</p>`,
    image: 'assets/age18.png',
    sources: [
      { text: 'KidCentral TN – Brain Development Adolescents (14-18 Years)', url: 'https://www.kidcentraltn.com/development/14-16-years/brain-development-adolescents-14-18-years.html' },
      { text: 'NAMI – Mental Health Conditions', url: 'https://www.nami.org/about-mental-illness/mental-health-conditions/' },
      { text: 'Reddit – For Parents of Older Teenagers', url: 'https://www.reddit.com/r/Parenting/comments/1ag945v/for_parents_of_older_teenagers_what_advice_do_you/' },
      { text: 'ScienceDirect – Gender Difference in the Change of Adolescents’ Mental Health', url: 'https://www.sciencedirect.com/science/article/pii/S187892932030027X' }
    ]
  },
  19: {
    tannerStage: 'Stage 5',
    cognitionHtml: `<p>Nineteen-year-olds refine adult cognition, integrating experience with analysis for real-world problems like career choices. They multitask effectively, using evidence in arguments. Metacognition supports self-improvement, like skill-building courses. Cognitive biases lessen, enhancing objectivity.</p>`,
    socialEmotionalHtml: `<p>Identity stabilizes, with focus on long-term relationships and goals. Independence full, but family advice valued. Emotional maturity handles stress better, though transitions like college can cause anxiety. Parenting: Act as mentor, discuss finances/health. Watch for depression (withdrawal), anxiety (overwhelm), or schizophrenia (reality loss)—promote counseling.</p>`,
    playBehaviorHtml: `<p>Leisure includes work-life balance, like hobbies or travel. Risks subside; encourage healthy choices. Tips: Guide without controlling, celebrate independence, teach resilience through challenges.</p>`,
    genderDifferencesHtml: `<p>Differences subtle: women often multitask better, men spatial skills. Mental health patterns persist but equalize with age. Support individual paths beyond gender norms.</p>`,
    neurodiversityHtml: `<p>ADHD 19-year-olds adapt to work/college with strategies; peer support groups help. Autistic adults find niches, but social fatigue lingers; accommodations key. Monitor co-occurring conditions.</p>`,
    maturationNotesHtml: `<p>Prefrontal full function by early 20s, optimizing executive skills. Neural stability supports lifelong learning.</p>`,
    image: 'assets/age19.png',
    sources: [
      { text: 'PMC – Maturation of the Adolescent Brain', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3621648/' },
      { text: 'Verywell Health – Early Signs and Symptoms of Schizophrenia', url: 'https://www.verywellhealth.com/early-signs-schizophrenia-5101519' },
      { text: 'Quora – Advice on Parenting Teens and 20-Year-Olds', url: 'https://www.quora.com/Is-there-any-advice-on-parenting-teens-and-20-year-olds' },
      { text: 'PMC – Gender Difference in the Change of Adolescents’ Mental Health', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8896070/' }
    ]
  },
  20: {
    tannerStage: 'Stage 5',
    cognitionHtml: `<p>Twenty-year-olds display mature cognition, synthesizing knowledge for innovative solutions, like business plans. They anticipate long-term consequences, using nuanced critical thinking. Metacognition drives continuous growth, adapting to challenges.</p>`,
    socialEmotionalHtml: `<p>Young adults at 20 establish independence, building careers/relationships. Emotional intelligence high, managing conflicts maturely. Stress from adulthood can trigger issues. Parenting: Provide occasional advice, respect boundaries. Signs: Schizophrenia onset (hallucinations, delusions), depression (hopelessness), anxiety (panic)—urge professional care. Celebrate achievements to affirm growth.</p>`,
    playBehaviorHtml: `<p>Focus on adult responsibilities, with recreation like fitness or social events. Balanced lifestyles emerge. Tips: Encourage self-care, financial independence, and positive networks.</p>`,
    genderDifferencesHtml: `<p>Gaps minimal; individual differences dominate. Persistent: women higher emotional expression, men risk tolerance. Equity in roles increases.</p>`,
    neurodiversityHtml: `<p>ADHD adults thrive with accommodations; self-management key. Autistic 20-year-olds advocate effectively, finding supportive environments. Watch for mental health overlaps like anxiety.</p>`,
    maturationNotesHtml: `<p>Brain reaches full maturity around 25, with optimized prefrontal-limbic integration for balanced decision-making and emotion regulation.</p>`,
    image: 'assets/age20.png',
    sources: [
      { text: 'Healthline – Teen Brain Development: Timeline, Effects, Factors', url: 'https://www.healthline.com/health/teen-brain-development' },
      { text: 'WHO – Mental Health of Adolescents', url: 'https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health' },
      { text: 'Children’s Hope Alliance – 25 Simple Parenting Tips', url: 'https://www.childrenshopealliance.org/archives/16953' },
      { text: 'Nature – Age at Onset of Mental Disorders Worldwide', url: 'https://www.nature.com/articles/s41380-021-01161-7' }
    ]
  }
};

// Export for module environments and attach to window for inline scripts.
if (typeof module !== 'undefined') {
  module.exports = { AGE_DATA };
}
if (typeof window !== 'undefined') {
  window.AGE_DATA = AGE_DATA;
}